sudo: false
branches:
  except:
    - gh-pages
cache: bundler
language: ruby
rvm:
  - 2.1
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake validate
  - bundle exec rake spec
  - bundle exec rake lint
